# Variables
@baseUrl = http://localhost:3333
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhkZmNlYjgwLTE5OWMtNDg4Zi04OTE4LWEwNjA5MTc1Mzk5YyIsImVtYWlsIjoiYWRtaW5pc3RyYWRvckBhZG1pbi5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NjUxNTE5MjAsImV4cCI6MTc2NTE1NTUyMH0.F63aQb6acKqu5sQdRxJc8IXcAzSuVe0kX9IXDzZPZC0

###

# create ticket
# @name createTicket
POST {{baseUrl}}/tickets
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "techId": "8717d531-97de-43f5-a1dd-e1bdcc20140d",
  "servicesIds": ["33807cc5-731e-4bf4-888c-d56a27745ef5", "08bc85dc-e13f-472d-a156-4d6cc026934e"]
}

###

# show client history of tickets
# @name showClientHistory
GET {{baseUrl}}/tickets/clientHistory
Authorization: Bearer {{token}}

###

# list tickets set to a tech
# @name showTechTicketsList
GET {{baseUrl}}/tickets/tech
Authorization: Bearer {{token}}

###

# list all tickets to admin
# @name listAllTickets
GET {{baseUrl}}/tickets/list
Authorization: Bearer {{token}}

###

# add services to a ticket
# @name addServicesToATicket
PUT {{baseUrl}}/tickets/addServices/fcb6c6e0-8115-46d1-b71e-6fb66e84359a
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "servicesIds": ["4878508a-2fd4-4005-8418-83fce08c0e50"]
}

###

# add services to a ticket
# @name addServicesToATicket
PUT {{baseUrl}}/tickets/status/fcb6c6e0-8115-46d1-b71e-6fb66e84359a
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "status": "aberto"
}