# Variables
@baseUrl = http://localhost:3333
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhkZmNlYjgwLTE5OWMtNDg4Zi04OTE4LWEwNjA5MTc1Mzk5YyIsImVtYWlsIjoiYWRtaW5pc3RyYWRvckBhZG1pbi5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3Njk2MzM2NzIsImV4cCI6MTc2OTYzNzI3Mn0.bnR3XVyD9t8PDl46Y2jASxRcNMqCMwjKIjzOlOFUqdQ

###

# create service
# @name createService
POST {{baseUrl}}/services
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "title": "Desentupir ralo",
  "price": 200.0
}

###

# list Services
# @name listServices
GET {{baseUrl}}/services/list
Authorization: Bearer {{token}}

###

# update service
# @name updateService
PUT {{baseUrl}}/services/ab068bb8-5df5-4ab3-a748-463f86395cca
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "title": "Desentupir cano",
  "price": 250.0
}

###

# deactivate service
# @name deactivateService
DELETE {{baseUrl}}/services/9386ea81-b6ad-4538-8c6c-c1afe6a5c720
Authorization: Bearer {{token}}
